import os
import subprocess
import json
import time
from pathlib import Path
from datetime import datetime, timezone
from packages.contracts.python import MotionScript, EventType, Layer

class RenderEngine:
    def __init__(self, ffmpeg_binary: str = "ffmpeg", ffprobe_binary: str = "ffprobe") -> None:
        self.ffmpeg_binary = ffmpeg_binary
        self.ffprobe_binary = ffprobe_binary

    def ms_to_ass_time(self, ms: int) -> str:
        """Converts milliseconds to ASS timestamp format (H:MM:SS.cs)."""
        cs = (ms // 10) % 100
        sec = (ms // 1000) % 60
        min_ = (ms // 60000) % 60
        hr = ms // 3600000
        return f"{hr}:{min_:02d}:{sec:02d}.{cs:02d}"

    def hex_to_ass_abgr(self, hex_color: str, alpha_percent: float = 100.0) -> str:
        """Converts hex color (e.g. #FFFFFF or #FF0000) to ASS format (&HAAABBGR)."""
        clean = hex_color.lstrip("#")
        if len(clean) == 3:
            clean = "".join(c * 2 for c in clean)
        r = clean[0:2]
        g = clean[2:4]
        b = clean[4:6]
        
        # ASS Alpha: 00 is opaque, FF is transparent
        alpha_val = int((1.0 - (alpha_percent / 100.0)) * 255)
        a = f"{alpha_val:02d}"
        
        return f"&H{a}{b}{g}{r}"

    def generate_ass(self, motion_script: MotionScript) -> str:
        """Generates ASS subtitles from MotionScript."""
        width = motion_script.global_settings.canvas.width
        height = motion_script.global_settings.canvas.height
        
        # 1. Script Info Section
        ass_lines = [
            "[Script Info]",
            "; Script generated by MotionAI RenderEngine",
            "ScriptType: v4.00+",
            f"PlayResX: {width}",
            f"PlayResY: {height}",
            "ScaledBorderAndShadow: yes",
            "",
            "[V4+ Styles]",
            "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding"
        ]

        # Load style preset settings
        from app.render.presets import StylePresetManager
        preset_name = motion_script.global_settings.motion_preset
        preset = StylePresetManager.get_preset(preset_name)

        font_family = preset.typography.font
        font_size = preset.typography.size
        base_color = self.hex_to_ass_abgr(preset.typography.color)
        outline = preset.typography.outline
        shadow = preset.typography.shadow
        margin_l = int(preset.safe_area.left)
        margin_r = int(preset.safe_area.right)
        margin_v = int(preset.safe_area.bottom)

        bold_str = str(preset.typography.weight)
        if bold_str.isdigit():
            bold_val = int(bold_str)
        elif bold_str.lower() in {"bold", "true"}:
            bold_val = -1
        else:
            bold_val = 0

        alignment = preset.typography.alignment
        alignment_code = 2
        if alignment == "left":
            alignment_code = 1
        elif alignment == "right":
            alignment_code = 3

        # Allow caption event payloads to override defaults (retains backward compatibility)
        caption_events = [e for e in motion_script.timeline if e.type == EventType.CAPTION]
        if caption_events:
            first_payload = caption_events[0].parsed_payload()
            font_family = getattr(first_payload, "font", font_family)
            font_size = getattr(first_payload, "size", font_size)
            
            color_hex = getattr(first_payload, "color", None)
            if color_hex:
                base_color = self.hex_to_ass_abgr(color_hex)
                
            alignment = getattr(first_payload, "alignment", alignment)
            if alignment == "left":
                alignment_code = 1
            elif alignment == "right":
                alignment_code = 3

        # Style definition line
        ass_lines.append(
            f"Style: Default,{font_family},{font_size},{base_color},&H000000FF,&H00000000,&H80000000,{bold_val},0,0,0,100,100,0,0,1,{outline},{shadow},{alignment_code},{margin_l},{margin_r},{margin_v},1"
        )
        ass_lines.append("")
        ass_lines.append("[Events]")
        ass_lines.append("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text")


        # Compile timeline events
        highlight_events = [e for e in motion_script.timeline if e.type == EventType.HIGHLIGHT]

        for cap in caption_events:
            cap_payload = cap.parsed_payload()
            text = cap_payload.text
            words = text.split()
            
            # Find active highlights for this caption
            cap_highlights = [
                h for h in highlight_events 
                if h.start_ms < cap.end_ms and h.end_ms > cap.start_ms
            ]

            # Generate segment splits for dynamic word coloring and animations
            splits = {cap.start_ms, cap.end_ms}
            for h in cap_highlights:
                splits.add(max(h.start_ms, cap.start_ms))
                splits.add(min(h.end_ms, cap.end_ms))
            
            sorted_splits = sorted(list(splits))
            
            for t_start, t_end in zip(sorted_splits, sorted_splits[1:]):
                if t_start >= t_end:
                    continue
                
                # Identify which words should be highlighted in this sub-interval
                active_color = None
                highlighted_indices = set()
                for h in cap_highlights:
                    if h.start_ms <= t_start and h.end_ms >= t_end:
                        highlight_payload = h.parsed_payload()
                        highlighted_indices.update(highlight_payload.indices)
                        active_color = self.hex_to_ass_abgr(highlight_payload.color)

                # Format the text with ASS tags
                formatted_words = []
                for idx, w in enumerate(words):
                    if idx in highlighted_indices and active_color:
                        # Determine highlight color with rotating support
                        if len(preset.highlight.colors) > 1:
                            color_idx = idx % len(preset.highlight.colors)
                            word_color = self.hex_to_ass_abgr(preset.highlight.colors[color_idx])
                        else:
                            word_color = active_color
                        
                        # Apply subtle scale-up for active word pop animation (e.g. Hormozi captions style)
                        if preset.animation.motion_preset in {"dynamic", "smooth"}:
                            formatted_words.append(f"{{\\1c{word_color}\\fscx115\\fscy115}}{w}{{\\1c{base_color}\\fscx100\\fscy100}}")
                        else:
                            formatted_words.append(f"{{\\1c{word_color}}}{w}{{\\1c{base_color}}}")
                    else:
                        formatted_words.append(w)
                
                segment_text = " ".join(formatted_words)
                
                # Apply Animation Preset tags
                anim_preset = getattr(cap_payload, "animation", "fade")
                if hasattr(anim_preset, "value"):
                    anim_preset = anim_preset.value
                else:
                    anim_preset = str(anim_preset)

                anim_tags = ""
                is_first_seg = (t_start == cap.start_ms)
                is_last_seg = (t_end == cap.end_ms)

                if anim_preset == "fade":
                    fade_in = 150 if is_first_seg else 0
                    fade_out = 150 if is_last_seg else 0
                    if fade_in > 0 or fade_out > 0:
                        anim_tags = f"{{\\fad({fade_in},{fade_out})}}"
                elif is_first_seg:
                    if anim_preset == "pop":
                        anim_tags = "{\\fscx110\\fscy110}{\\t(0,100,\\fscx100\\fscy100)}"
                    elif anim_preset == "scale":
                        anim_tags = "{\\fscx0\\fscy0}{\\t(0,150,\\fscx100\\fscy100)}"
                    elif anim_preset == "slide":
                        anim_tags = "{\\an2}{\\move(540,1000,540,960,0,200)}"
                    elif anim_preset == "bounce":
                        anim_tags = "{\\t(0,100,\\fscy115\\fscx105)}{\\t(100,200,\\fscy100\\fscx100)}"
                    elif anim_preset == "rotate":
                        anim_tags = "{\\frz-5}{\\t(0,150,\\frz0)}"
                    elif anim_preset == "elastic":
                        anim_tags = "{\\fscx0\\fscy0}{\\t(0,100,\\fscx120\\fscy120)}{\\t(100,180,\\fscx95\\fscy95)}{\\t(180,250,\\fscx100\\fscy100)}"
                
                full_text = f"{anim_tags}{segment_text}"
                
                start_str = self.ms_to_ass_time(t_start)
                end_str = self.ms_to_ass_time(t_end)
                ass_lines.append(
                    f"Dialogue: 0,{start_str},{end_str},Default,,0,0,0,,{full_text}"
                )

        return "\n".join(ass_lines)

    def probe_metadata(self, filepath: str) -> dict:
        """Uses ffprobe to extract video metadata."""
        cmd = [
            self.ffprobe_binary,
            "-v", "error",
            "-select_streams", "v:0",
            "-show_entries", "stream=width,height,codec_name,duration",
            "-show_entries", "format=size",
            "-of", "json",
            filepath
        ]
        try:
            res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
            data = json.loads(res.stdout)
            stream = data.get("streams", [{}])[0]
            fmt = data.get("format", {})
            return {
                "width": stream.get("width"),
                "height": stream.get("height"),
                "codec": stream.get("codec_name"),
                "duration_s": float(fmt.get("duration", 0.0)),
                "size_bytes": int(fmt.get("size", 0)),
            }
        except Exception as exc:
            # Safe fallbacks if ffprobe fails or is missing locally
            return {
                "width": 1080,
                "height": 1920,
                "codec": "h264",
                "duration_s": 0.0,
                "size_bytes": 0,
            }

    def render(
        self,
        motion_script: MotionScript,
        video_path: str,
        output_path: str,
        progress_callback=None
    ) -> dict:
        """Executes the pipeline stages to render a video with subtitles."""
        if progress_callback:
            progress_callback("Preparing", 5)

        if not os.path.exists(video_path):
            raise FileNotFoundError(f"Input video not found: {video_path}")

        # Stage 5: Generate ASS Subtitles
        if progress_callback:
            progress_callback("Generating ASS", 15)
        ass_content = self.generate_ass(motion_script)
        
        # Save temporary ASS file
        temp_ass = Path(output_path).with_suffix(".ass")
        temp_ass.write_text(ass_content, encoding="utf-8")
        
        # Stage 6: Prepare FFmpeg filter graph
        if progress_callback:
            progress_callback("Rendering", 30)

        width = motion_script.global_settings.canvas.width
        height = motion_script.global_settings.canvas.height
        
        # Escape path for FFmpeg subtitles filter
        ass_filter_path = str(temp_ass.resolve()).replace("\\", "/").replace(":", "\\:")
        filter_graph = (
            f"scale=w={width}:h={height}:force_original_aspect_ratio=decrease,"
            f"pad={width}:{height}:(ow-iw)/2:(oh-ih)/2,"
            f"subtitles='{ass_filter_path}'"
        )

        # Stage 7-12: Execute rendering and encoding
        cmd = [
            self.ffmpeg_binary,
            "-y",
            "-i", video_path,
            "-vf", filter_graph,
            "-c:v", "libx264",
            "-preset", "fast",
            "-crf", "22",
            "-c:a", "aac",
            output_path
        ]

        if progress_callback:
            progress_callback("Encoding", 60)

        start_time = time.monotonic()
        try:
            subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
        except subprocess.CalledProcessError as err:
            if temp_ass.exists():
                temp_ass.unlink()
            raise RuntimeError(f"FFmpeg render failure: {err.stderr.decode(errors='replace')}") from err

        render_duration_ms = int((time.monotonic() - start_time) * 1000)

        # Clean up temporary ASS file
        if temp_ass.exists():
            temp_ass.unlink()

        # Probe output details
        meta = self.probe_metadata(output_path)
        meta["render_duration_ms"] = render_duration_ms

        return meta
