import React from "react";

/**
 * The one CaptionsEasy logo, used everywhere a logo appears. It renders the committed brand files in
 * public/brand/ (generated by scripts/brand/make-brand-kit.cjs), so the site, favicon and downloads match exactly.
 *   variant: "full" = mark + wordmark, "mark" = the three caption bars, "word" = wordmark only
 *   tone:    "dark" for light backgrounds, "light" for dark backgrounds
 */
const ASSETS = {
  full: { file: "captionseasy-logo", ratio: 735.4 / 125.8 },
  word: { file: "captionseasy-wordmark", ratio: 648.4 / 118.6 },
  mark: { file: "captionseasy-icon", ratio: 1 },
} as const;

export function Logo({
  variant = "full",
  tone = "dark",
  height = 28,
  className = "",
}: {
  variant?: keyof typeof ASSETS;
  tone?: "dark" | "light";
  height?: number;
  className?: string;
}) {
  const a = ASSETS[variant];
  const src = `/brand/${a.file}${tone === "light" ? "-light" : ""}.svg`;
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img src={src} alt="CaptionsEasy" width={Math.round(height * a.ratio)} height={height} className={`block shrink-0 select-none ${className}`} style={{ height, width: "auto" }} draggable={false} />
  );
}
